-- Script generado automáticamente
DELETE FROM ejercicios;

-- Dimensión 1, Nivel 1: Comprensión del sistema de numeración
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Â¿QuÃ© fracciÃ³n es igual a 2/4?', 'Comprensión del sistema de numeración', '1/2;2/3;3/4;1/3', 1, 1, 1, 2);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Â¿QuÃ© fracciÃ³n representa tres cuartos?', 'Comprensión del sistema de numeración', '3/2;3/4;4/3;1/4', 2, 1, 1, 2);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Â¿QuÃ© nÃºmero es mayor?', 'Comprensión del sistema de numeración', '0.6;0.8;0.75;0.7', 2, 1, 1, 2);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Â¿CuÃ¡l nÃºmero es equivalente a 0.5?', 'Comprensión del sistema de numeración', '1/5;1/2;2/5;3/4', 2, 1, 1, 2);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('0.9 Elevada Ã“ptima Â¿QuÃ© fracciÃ³n representa 0.75?', 'Comprensión del sistema de numeración', '3/4;2/3;1/4;4/3', 1, 1, 1, 3);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Â¿CuÃ¡l es el valor posicional del 8 en 384?', 'Comprensión del sistema de numeración', '8 unidades;8 decenas;8 centenas;8 millares', 2, 1, 1, 2);

-- Dimensión 1, Nivel 2: Operaciones básicas
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Ã“ptima Media Â¿CuÃ¡l es el resultado de 3 Ã— (4 + 2)?', 'Operaciones básicas', '18;12;14;20', 1, 2, 1, 3);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Â¿CuÃ¡l es el resultado de la siguiente multiplicaciÃ³n 9 Ã— 6?', 'Operaciones básicas', '45;54;63;36', 2, 2, 1, 2);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Â¿CuÃ¡l es el resultado de esta resta 25 â€“ 8?', 'Operaciones básicas', '16;17;18;19', 2, 2, 1, 2);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Si tengo 48 dulces y los reparto entre 8 niÃ±os, Â¿cuÃ¡ntos dulces recibe cada uno?', 'Operaciones básicas', '8;7;6;5', 1, 2, 1, 3);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Â¿CuÃ¡l es el resultado de esta divisiÃ³n 36 Ã· 4?', 'Operaciones básicas', '8;9;6;7', 2, 2, 1, 2);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Â¿CuÃ¡l es el resultado correcto de (15 + 9) Ã· 3?', 'Operaciones básicas', '6;7;8;9', 3, 2, 1, 3);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Â¿QuÃ© nÃºmero falta en esta divisiÃ³n? ___ Ã· 5 = 7', 'Operaciones básicas', '30;35;40;25', 2, 2, 1, 3);

-- Dimensión 1, Nivel 3: Cálculo mental
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Si 5 Ã— 5 = 25, entonces Â¿CuÃ¡l es el resultado de 5 Ã— 6 = ?', 'Cálculo mental', '30;35;36;25', 1, 3, 1, 2);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Â¿CuÃ¡l es el resultado de 9 Ã— 8 = ?', 'Cálculo mental', '64;70;72;81', 3, 3, 1, 3);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Â¿CuÃ¡l es el resultado de 144 Ã· 12?', 'Cálculo mental', '11;12;13;14', 2, 3, 1, 3);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Calcula mentalmente: (25 + 25) Ã— 2 = ?', 'Cálculo mental', '80;90;100;110', 3, 3, 1, 3);

-- Dimensión 2, Nivel 1: Figuras planas y cuerpos geométricos
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Â¿QuÃ© figura tiene 12 aristas y 8 vÃ©rtices?', 'Figuras planas y cuerpos geométricos', 'Prisma rectangular;Cubo;PirÃ¡mide;Cono', 1, 1, 2, 3);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Ã“ptima Â¿CuÃ¡l figura tiene muchos ejes de simetrÃ­a, como infinitos?', 'Figuras planas y cuerpos geométricos', 'CÃ­rculo;Cuadrado;TriÃ¡ngulo;RectÃ¡ngulo', 1, 1, 2, 3);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Â¿CuÃ¡ntos lados tiene un pentÃ¡gono?', 'Figuras planas y cuerpos geométricos', '4;5;6;7', 2, 1, 2, 2);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Â¿CuÃ¡l de las siguientes figuras puedo rodar fÃ¡cilmente?', 'Figuras planas y cuerpos geométricos', 'Cubo;Esfera;PirÃ¡mide;Prisma', 2, 1, 2, 2);

-- Dimensión 2, Nivel 2: propiedades de formas
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Â¿QuÃ© unidad se usamos para medir el Ã¡rea?', 'propiedades de formas', 'cm;m;cmÂ²;L', 3, 2, 2, 2);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Media Â¿QuÃ© figura tiene una sola lÃ­nea de simetrÃ­a?', 'propiedades de formas', 'CÃ­rculo;TriÃ¡ngulo isÃ³sceles;Cuadrado;RectÃ¡ngulo', 2, 2, 2, 3);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Un rectÃ¡ngulo mide 10 cm por 5 cm, Â¿CuÃ¡l es su Ã¡rea?', 'propiedades de formas', '15 cmÂ²;20 cmÂ²;25 cmÂ²;50 cmÂ²', 4, 2, 2, 3);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Si cada lado de un cuadrado mide 5 cm, Â¿CuÃ¡nto su perÃ­metro?', 'propiedades de formas', '10 cm;15 cm;20 cm;25 cm', 3, 2, 2, 2);

-- Dimensión 2, Nivel 3: Ubicación espacial
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('En un plano cartesiano, Â¿CÃ³mo se llama el eje horizontal?', 'Ubicación espacial', 'Eje X;Eje Y;Eje Z;Eje N', 1, 3, 2, 3);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Ã“ptima En un plano cartesiano, Â¿CÃ³mo se llama el punto (0,0) donde empiezan los ejes?', 'Ubicación espacial', 'Inicio;Centro;Origen;Base', 3, 3, 2, 3);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Media Â¿QuÃ© palabra usamos para decir que algo estÃ¡ â€œen medio de dos cosasâ€?', 'Ubicación espacial', 'Dentro;DetrÃ¡s;Entre;Al lado', 3, 3, 2, 2);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('El punto A estÃ¡ en (3,3) y el punto B en (6,6), Â¿QuÃ© tipo de movimiento hizo?', 'Ubicación espacial', 'Horizontal;Vertical;Diagonal;Circular', 3, 3, 2, 3);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Si un punto estÃ¡ en (4,5) y baja hasta (4,2), Â¿En quÃ© direcciÃ³n se moviÃ³?', 'Ubicación espacial', 'Norte;Sur;Este;Oeste', 2, 3, 2, 3);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('En un mapa, el lago estÃ¡ al Oeste de la montaÃ±a y la escuela estÃ¡ al sur del lago. Â¿DÃ³nde estÃ¡ la escuela respecto a la montaÃ±a?', 'Ubicación espacial', 'Suroeste;Noreste;Sureste;Noroeste', 3, 3, 2, 2);

-- Dimensión 3, Nivel 1: Medición
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Ã“ptima Si una caja pesa 4 kg y otra pesa el doble, Â¿CuÃ¡nto pesan juntas?', 'Medición', '6 kg;8 kg;10 kg;12 kg', 4, 1, 3, 3);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Si una cuerda mide 2 metros, Â¿CuÃ¡ntos centÃ­metros mide?', 'Medición', '20 cm;200 cm;2,000 cm;20,000 cm', 2, 1, 3, 3);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Media Si un litro de jugo cuesta $25, Â¿CuÃ¡nto cuestan 4 litros?', 'Medición', '$50;$75;$100;$125', 3, 1, 3, 2);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Media Si un envase tiene 250 mililitros y llenas 4 envases, Â¿CuÃ¡ntos mililitros hay en total?', 'Medición', '500;750;1,000;1,250', 3, 1, 3, 2);

-- Dimensión 3, Nivel 2: Recolección
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Si cada figura [imagen de referencia] representa 4 peces y hay 6 figuras. Â¿CuÃ¡ntos peces hay en total?', 'Recolección', '20;22;24;26', 3, 2, 3, 2);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Si una cuerda de 3 metros se corta en 5 partes iguales, Â¿CuÃ¡nto mide cada parte?', 'Recolección', '30 cm;50 cm;60 cm;70 cm', 3, 2, 3, 3);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Si una manzana pesa 200 gramos, Â¿CuÃ¡nto pesan 5 manzanas iguales?', 'Recolección', '500 g;1 kg;1,000 g;2,000 g', 3, 2, 3, 3);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('En una encuesta, 10 niÃ±os prefieren leche y 5 jugo. Â¿QuÃ© porcentaje prefiere leche?', 'Recolección', '30%;40%;60%;66%     No aplica', 3, 2, 3, 3);

-- Dimensión 3, Nivel 3: Lectura de información
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('En una lista de asistencia se escribiÃ³ que los lunes van a la escuela 18 niÃ±os, los martes van 20 niÃ±os, y los miÃ©rcoles van 22 niÃ±os. Â¿CuÃ¡l es la tendencia?', 'Lectura de información', 'Sube;Baja;Se mantiene;Irregular', 1, 3, 3, 3);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Si en una grÃ¡fica una barra mide 20 cm y otra 15 cm, Â¿quÃ© proporciÃ³n hay entre ambas?', 'Lectura de información', '2/3;3/4;4/5;5/6', 3, 3, 3, 3);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Si una barra representa 5 unidades y hay 6 barras, Â¿cuÃ¡ntas unidades en total?', 'Lectura de información', '25;30;35;40', 2, 3, 3, 2);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Se hizo una grÃ¡fica de pastel de las ventas que se hicieron en varios meses, y se registrÃ³ que en enero fueron 20, en febrero 25, y en marzo 15. Â¿QuÃ© mes tiene menos ventas?', 'Lectura de información', 'Enero;Febrero;Marzo;Igual', 3, 3, 3, 2);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('comÃºn Elevada Ã“ptima En una tabla, Marta tiene 9 puntos, Luis tiene 6 y Ana tiene 12. Â¿QuiÃ©n tiene mÃ¡s diferencia de puntos comparado con Luis?', 'Lectura de información', 'Marta;Ana;Ninguno;Los dos', 2, 3, 3, 3);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('En una grÃ¡fica de barras, la diferencia entre â€œlecheâ€ (8) y â€œjugoâ€ (5) es:', 'Lectura de información', '2;3;4;5', 2, 3, 3, 2);

-- Dimensión 4, Nivel 1: Sentido numérico
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Si 1/2 = 0.5, Â¿cuÃ¡l fracciÃ³n es mÃ¡s cercana a 1?', 'Sentido numérico', '1/3;2/3;3/4;1/4', 3, 1, 4, 3);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Estima el resultado de esta suma: 198 + 205 = ?', 'Sentido numérico', '300;400;500;200', 2, 1, 4, 2);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Â¿QuÃ© nÃºmero es menor 3/4 o 2/4?', 'Sentido numérico', '3/4;2/4;Son iguales;No se puede comparar', 2, 1, 4, 2);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Â¿QuÃ© opciÃ³n representa mejor el doble de 25?', 'Sentido numérico', '30;40;50;60', 3, 1, 4, 2);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('0.75 Elevada Ã“ptima Â¿CuÃ¡l es el valor aproximado de 98 Ã· 5?', 'Sentido numérico', '10;15;20;25', 3, 1, 4, 3);

-- Dimensión 4, Nivel 2: Introducción a la probabilidad
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Baja En una bolsa con 5 bolas rojas y 5 verdes, Â¿cuÃ¡l es la probabilidad de sacar roja?', 'Introducción a la probabilidad', '1/5;1/2;2/3;1/10', 2, 2, 4, 2);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Si tienes una moneda, Â¿quÃ© probabilidad hay de que salga Ã¡guila?', 'Introducción a la probabilidad', '1/2;1/3;1/4;1', 1, 2, 4, 2);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Media Si un dado tiene 6 caras y todas diferentes, Â¿es posible sacar el nÃºmero 7?', 'Introducción a la probabilidad', 'SÃ­;No;A veces;Solo si repites', 2, 2, 4, 2);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Ã“ptima En una caja hay 8 pelotas verdes y 2 azules. Â¿CuÃ¡l es la probabilidad de sacar azul?', 'Introducción a la probabilidad', '2/10;1/2;8/10;10/2', 1, 2, 4, 3);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Si en una bolsa hay 3 caramelos verdes, 2 rojos y 1 azul, Â¿cuÃ¡l es el color mÃ¡s probable?', 'Introducción a la probabilidad', 'Verde;Rojo;Azul;Todos igual', 1, 2, 4, 3);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Si lanzas un dado, Â¿quÃ© probabilidad hay de que salga un nÃºmero menor que 3?', 'Introducción a la probabilidad', '1/6;2/6;3/6;4/6', 2, 2, 4, 2);

-- Dimensión 4, Nivel 3: Reconocimiento de patrones
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Â¿CuÃ¡l es el nÃºmero que sigue: 1, 4, 7, 10, 13, __?', 'Reconocimiento de patrones', '14;15;16;19      No aplica', 2, 3, 4, 2);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Encuentra y escribe el nÃºmero que falta al final: 1, 1, 2, 3, 5, 8, _.', 'Reconocimiento de patrones', '10;11;13;15      No aplica', 3, 3, 4, 2);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Escribe el nÃºmero que falta: 2, 3, 5, 8, 12, _.', 'Reconocimiento de patrones', '14;15;17;18      No aplica', 2, 3, 4, 2);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Â¿CuÃ¡l es el prÃ³ximo nÃºmero que va despuÃ©s del nÃºmero 15: 3, 6, 9, 12, 15, _?', 'Reconocimiento de patrones', '16;18;20;24      No aplica', 2, 3, 4, 1);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Referencia a imagen: Reconocimiento de patrones y regularidades Imagen de referencia Respuesta correcta Dificultad (niÃ±os de 1Â° a 3Â°) Dificultad (niÃ±os de 4Â° a 6Â°) Â¿QuÃ© figura va despuÃ©s? â—‹â—â—‹â—â—‹ __ ?', 'Reconocimiento de patrones', 'â—‹  â€ƒB)   â—Ž   â€ƒC)   â—   â€ƒD)   â—’        No aplica      C)   â—      Baja      Muy baja        Â¿CuÃ¡l es el prÃ³ximo nÃºmero en la sucesiÃ³n 2, 4, 6, 8, __?     A)9;10;12 D14      No aplica      B)10      Baja      Muy baja         Â¿QuÃ© figura sigue en esta serie:   â–²  ,   â–¼  ,   â–²  ,   â–¼  ,   â–²  , __ A)   â–²   â€ƒB) â—‹ â€ƒC)   â–¼   â€ƒD) â–¡       No aplica      C)   â–¼      Baja      Muy baja        ContinÃºa la siguiente serie de colores:     â–­â–­     â–¯ â–­â–­â–¯â–­â–­     __ a)   â–¯   â€ƒb)   â–­     â€ƒc)   â–¬  â€ƒd)   â–®      No aplica      A)   â–¯      Media      Baja        Â¿CuÃ¡l es el prÃ³ximo de esta sucesiÃ³n numÃ©rica 5, 10, 15, 20, __?        25 B) 30 C) 35;40          No aplica', 1, 3, 4, 1);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Referencia a imagen: Â¿QuÃ© botÃ³n sigue despuÃ©s Imagen de Story Pin Imagen de Story Pin Imagen de Story Pin Imagen de Story Pin Imagen de Story Pin Imagen de Story Pin Imagen de Story Pin Imagen de Story Pin ______.', 'Reconocimiento de patrones', 'Imagen de Story Pin;Imagen de Story Pin;Imagen de Story Pin;Imagen de Story Pin         Imagen de Story Pin        Imagen de Story Pin     Imagen de Story Pin        Imagen de Story Pin', 2, 3, 4, 1);

-- Dimensión 5, Nivel 1: Resolución de problemas
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Si a un nÃºmero le sumas 4, y ese resultado lo multiplicas por 2 menos 3. Â¿CuÃ¡l es ese nÃºmero? 5 B) 6 C )7 D) 8 No aplica', 'Resolución de problemas', '7      Elevada      Ã“ptima         En una caja hay caramelos, pero se reparten entre 4 niÃ±os y cada uno recibe 3. Â¿CuÃ¡ntos caramelos habÃ­a?    A) 10;11;12;13', 3, 1, 5, 2);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Media Si un dado tiene 6 caras y todas diferentes, Â¿es posible sacar el nÃºmero 7?', 'Resolución de problemas', 'SÃ­;No;A veces;Solo si repites', 2, 1, 5, 2);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Si en una bolsa hay 3 caramelos verdes, 2 rojos y 1 azul, Â¿cuÃ¡l es el color mÃ¡s probable?', 'Resolución de problemas', 'Verde;Rojo;Azul;Todos igual', 1, 1, 5, 3);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Si lloviÃ³ 5 dÃ­as seguidos, Â¿quÃ© probabilidad hay de que maÃ±ana tambiÃ©n llueva?', 'Resolución de problemas', 'Muy alta;Media;Muy baja;Ninguna', 1, 1, 5, 2);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Si a un nÃºmero le sumas 15, y el resultado es 22. Â¿CuÃ¡l es ese nÃºmero? _ + 15= 22', 'Resolución de problemas', '6;7;8;9      No aplica', 2, 1, 5, 2);
INSERT INTO ejercicios (pregunta, descripcion, opciones_respuestas, num_respuesta, nivel_id, dimension_id, dificultad) VALUES ('Â¿QuÃ© nÃºmero falta en esta resta _ - 8=12', 'Resolución de problemas', '18;19;20;21      No aplica', 3, 1, 5, 2);

-- ADVERTENCIA: No hay ejercicios para Aplicación de los conocimientos
-- ADVERTENCIA: No hay ejercicios para Desarrollo de estrategias
