/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.panaderiamatemagica.core.visual;
import java.awt.CardLayout; 
import javax.swing.JPanel;
/**
 *
 * @author user
 */
public class PantallaPrincipalVista extends javax.swing.JFrame {
    
    private CardLayout listaPantallas;
    
    public PantallaPrincipalVista() {
        initComponents();
        configurarListaPantallas();
    }
    private void configurarListaPantallas(){
        //Se crea una instancia de una lista de pantallas 
        listaPantallas = new CardLayout();
        
        //Se le asigna la lista de pantallas a monitor que es el panel que ocupa toda la pantalla
        //asi las pantallas que se guarden en listaPantallas se van a mostrar en ese panel del JFrame principal
        monitor.setLayout(listaPantallas);
        setLocationRelativeTo(null);
    }
     public void mostrarPanel(String nombrePanel) {
        listaPantallas.show(monitor, nombrePanel);
    }
    
    public void agregarPanel(JPanel panel, String nombre) {
        monitor.add(panel, nombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        monitor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        monitor.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout monitorLayout = new javax.swing.GroupLayout(monitor);
        monitor.setLayout(monitorLayout);
        monitorLayout.setHorizontalGroup(
            monitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 845, Short.MAX_VALUE)
        );
        monitorLayout.setVerticalGroup(
            monitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(monitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(monitor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel monitor;
    // End of variables declaration//GEN-END:variables
}
