/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.panaderiamatemagica.autenticacion.vista;

import com.panaderiamatemagica.core.RouterControlador;
import com.panaderiamatemagica.core.visual.componentes.FondoPanel;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class FondoAutenticacionVista extends javax.swing.JPanel {
    private RouterControlador router;
    private CardLayout pantallasAutenticacion;

    /**
     * Creates new form FondoAutenticacionVista
     */
    public FondoAutenticacionVista(RouterControlador router) {
        this.router = router;
        initComponents();
        inicializarPantallas();

        // Configuración básica sin MigLayout para evitar errores
        // Si tienes la imagen, descomenta la siguiente línea y ajusta si es necesario
        // FondoPanel fondoPanel = new FondoPanel("fondoAutenticacion.jpg");
        // this.add(fondoPanel); // O configurar como background si es posible
    }

    private void inicializarPantallas() {
        pantallasAutenticacion = new CardLayout();
        monitor.setLayout(pantallasAutenticacion);
    }

    public void agregarPanel(JPanel panel, String nombrePanel) {
        monitor.add(panel, nombrePanel);
    }

    public void mostrarPanel(String nombrePanel) {
        pantallasAutenticacion.show(monitor, nombrePanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        monitor = new javax.swing.JPanel();
        botonVolver = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(833, 615));
        setBackground(new java.awt.Color(255, 204, 153)); // Color de fondo por defecto

        monitor.setBackground(new java.awt.Color(153, 102, 0));

        javax.swing.GroupLayout monitorLayout = new javax.swing.GroupLayout(monitor);
        monitor.setLayout(monitorLayout);
        monitorLayout.setHorizontalGroup(
                monitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 320, Short.MAX_VALUE));
        monitorLayout.setVerticalGroup(
                monitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 440, Short.MAX_VALUE));

        botonVolver.setBackground(new java.awt.Color(255, 0, 0));
        botonVolver.setText("VOLVER");
        botonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonVolverMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonVolverMouseExited(evt);
            }
        });
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(256, 256, 256) // Centrado aproximado
                                .addComponent(monitor, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(257, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 96,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(monitor, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50,
                                        Short.MAX_VALUE)
                                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 57,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)));
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botonVolverActionPerformed
        router.mostrarInicioVista();
    }// GEN-LAST:event_botonVolverActionPerformed

    private void botonVolverMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_botonVolverMouseEntered
        botonVolver.setBackground(new Color(255, 138, 183));
    }// GEN-LAST:event_botonVolverMouseEntered

    private void botonVolverMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_botonVolverMouseExited
        botonVolver.setBackground(new Color(255, 0, 0));
    }// GEN-LAST:event_botonVolverMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVolver;
    private javax.swing.JPanel monitor;
    // End of variables declaration//GEN-END:variables
}
