/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.panaderiamatemagica.autenticacion.vista;

import com.panaderiamatemagica.autenticacion.controladores.alumnos.AlumnoControadorInicioSesion;
import com.panaderiamatemagica.autenticacion.controladores.alumnos.RouterAutenticacionControlador;
import com.panaderiamatemagica.core.RouterControlador;
import com.panaderiamatemagica.core.visual.componentes.FondoPanel;
import java.awt.Color;
import javax.swing.JTextField;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author User
 */
public class InicioSesionVista extends javax.swing.JPanel {

    private RouterControlador routerP;
    private RouterAutenticacionControlador routerA;
    private AlumnoControadorInicioSesion objetoControlador;
    
public InicioSesionVista(RouterControlador routerP, RouterAutenticacionControlador routerA) {
    this.routerP = routerP;
    this.routerA = routerA;
    // Llamamos al constructor del controlador que ahora SOLO espera la vista (this)
    objetoControlador = new AlumnoControadorInicioSesion(this);

    initComponents();
    
    FondoPanel fondoPanel = new FondoPanel("Panel Ovalado.jpg");
        fondoPanel.setLayout(new MigLayout("fill, insets 0", "[grow]", "[grow]"));
    
    // Configurar MigLayout en este panel principal
    setLayout(new java.awt.BorderLayout());
    
    // Agregar el fondo primero
    add(fondoPanel, java.awt.BorderLayout.CENTER);
    remove(titulo);
    remove(apodo);
    remove(cajaTexto);
    remove(botonIniciarSesion);
    remove(label1);
    remove(label2);
    remove(label3);
    
    fondoPanel.add( titulo, "pos 14% 3%, w 450:450:450 , h 60:60:60");
    fondoPanel.add(apodo , "pos 12.5% 18.18%, w 230:230:230, h 50:50:50");
    fondoPanel.add(cajaTexto , "pos 15.63% 25.76%,w 450:450:450, h 80:80:80");
    fondoPanel.add(botonIniciarSesion , "pos 20.31% 48.48%, w 370:370:370, h 150:150:150");
    fondoPanel.add(label1 , "pos 28.13% 75.76%, w 280:280:280, h 30:30:30");
    fondoPanel.add(label2 , "pos 34.38% 80.30%, w 230:230:230, h 30:30:30");
    fondoPanel.add(label3 , "pos 28.13% 83.33%, w 280:280:280 , h 30:30:30");
            
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    //todo este bloque me lo dio la ia por un error que me daba de inicializacion.
    // como no he estudiado graficas no se que hace la verdad.
    //-------------------------------------
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonIniciarSesion = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        cajaTexto = new javax.swing.JTextField();
        apodo = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 228, 171));
        setPreferredSize(new java.awt.Dimension(640, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonIniciarSesion.setBackground(new java.awt.Color(84, 180, 183));
        botonIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        botonIniciarSesion.setForeground(new java.awt.Color(0, 0, 0));
        botonIniciarSesion.setText("INICIAR SESIÓN");
        botonIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonIniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonIniciarSesionMouseExited(evt);
            }
        });
        botonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarSesionActionPerformed(evt);
            }
        });
        add(botonIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 370, 150));

        titulo.setFont(new java.awt.Font("Showcard Gothic", 0, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("INICIAR SESION");
        add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 450, 60));

        cajaTexto.setBackground(new java.awt.Color(255, 255, 255));
        cajaTexto.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        cajaTexto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 3));
        add(cajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 450, 80));

        apodo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        apodo.setForeground(new java.awt.Color(0, 0, 0));
        apodo.setText("APODO");
        add(apodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 230, 50));

        label3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        label3.setForeground(new java.awt.Color(133, 47, 27));
        label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label3.setText("<html><u>Regístrate</u></html>");
        label3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, 280, 30));

        label2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        label2.setForeground(new java.awt.Color(0, 0, 0));
        label2.setText("¿No tienes una cuenta?");
        add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 230, -1));

        label1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(133, 47, 27));
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("<html><u>¿Olvidaste tu contraseña?</u></html>");
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 280, 30));
    }// </editor-fold>//GEN-END:initComponents

 //-----------------------------------------------------------------------
    
    private void botonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarSesionActionPerformed
        // condicion para el inicio de sesion
        if (objetoControlador.validarUsuario()) {
            routerP.mostrarSeleccionDimensionVista();
        }
                
        
    }//GEN-LAST:event_botonIniciarSesionActionPerformed

    private void botonIniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIniciarSesionMouseEntered
        botonIniciarSesion.setBackground(new Color(85, 208, 82));         
    }//GEN-LAST:event_botonIniciarSesionMouseEntered

    private void botonIniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIniciarSesionMouseExited
        botonIniciarSesion.setBackground(new Color (117,183,168));
    }//GEN-LAST:event_botonIniciarSesionMouseExited

    //get
    public String getTxtapodo(){
        return cajaTexto.getText(); 
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apodo;
    private javax.swing.JButton botonIniciarSesion;
    private javax.swing.JTextField cajaTexto;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
