/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.panaderiamatemagica.autenticacion.vista;
import com.panaderiamatemagica.autenticacion.controladores.administradores.AdministradorControladorInicioSesion;
import com.panaderiamatemagica.core.RouterControlador;
import com.panaderiamatemagica.core.visual.componentes.FondoPanel;
import javax.swing.JTextField;
import net.miginfocom.swing.MigLayout;
/**
 *
 * @author User
 */
public class InicioSesionAdminVista extends javax.swing.JPanel {
    private RouterControlador router;
    private AdministradorControladorInicioSesion controlador;
    
    
    /**
     * Creates new form InicioSesionAdminVista
     */
    public InicioSesionAdminVista(RouterControlador router) {
        // inicializamos el controlador
        controlador = new AdministradorControladorInicioSesion(this
                ,router.getListaProfesores());
        
        this.router = router;
        initComponents();
    FondoPanel fondoPanel = new FondoPanel("Panel Ovalado.jpg");
    fondoPanel.setLayout(new MigLayout("fill, insets 0", "[grow]", "[grow]"));
    
    // Configurar MigLayout en este panel principal
    setLayout(new java.awt.BorderLayout());
    
    // Agregar el fondo primero
    add(fondoPanel, java.awt.BorderLayout.CENTER);
    
    // Remover componentes del diseño original
    remove(label1);
    remove(label2);
    remove(txt1);
    remove(txt2);
    remove(boton);
    
    // Agregar componentes al fondoPanel con posiciones específicas
    fondoPanel.add(label1, "pos 34.37% 9.09%, w 170:170:170, h 60:60:60");
    fondoPanel.add(label2,"pos 28% 40%, w 250:250:250, h 60:60:60");
    fondoPanel.add(txt1, "pos 12.5% 25.76%, w 453:453:453, h 37:37:37");
    fondoPanel.add(txt2,"pos 12.5% 57.58%, w 453:453:453, h 37:37:37");
    fondoPanel.add(boton, "pos 21.88% 77.27%, w 326:326:326, h 53:53:53");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton = new javax.swing.JButton();
        txt2 = new javax.swing.JTextField();
        label2 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        label1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 228, 196));
        setPreferredSize(new java.awt.Dimension(640, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton.setBackground(new java.awt.Color(84, 180, 183));
        boton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        boton.setForeground(new java.awt.Color(0, 0, 0));
        boton.setText("INGRESAR");
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });
        add(boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 326, 53));

        txt2.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        txt2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ActionPerformed(evt);
            }
        });
        add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 453, 37));

        label2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        label2.setForeground(new java.awt.Color(0, 0, 0));
        label2.setText("CONTRASEÑA");
        add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 268, 250, 60));

        txt1.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        txt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 453, 37));

        label1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        label1.setForeground(new java.awt.Color(0, 0, 0));
        label1.setText("USUARIO");
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 170, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
        // aqui va la loguica del inicio del profe.
        if (controlador.validarInicioSesion()) {
            router.mostrarAdminVista();
            vaciarTxtFields();
        }
        
    }//GEN-LAST:event_botonActionPerformed

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2ActionPerformed

    
    // get
    public String getTxtcontrasenna() {
        return txt2.getText();
    }
    
    public String getTxtusuarioProfesor() {
        return txt1.getText();
    }    
    
    private void vaciarTxtFields(){
        txt1.setText("");
        txt2.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    // End of variables declaration//GEN-END:variables
}
