/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.panaderiamatemagica.autenticacion.vista;
import com.panaderiamatemagica.autenticacion.controladores.alumnos.RouterRolControlador;
import com.panaderiamatemagica.core.visual.componentes.PanelConFondoVista;
import com.panaderiamatemagica.core.RouterControlador;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author User
 */
public class PantallaAutenticacionVista extends PanelConFondoVista {
    private RouterControlador router;
    private RouterRolControlador routerRolControlador;
    private CardLayout pantallasAutenticacion;
    
    public PantallaAutenticacionVista(RouterControlador router, RouterRolControlador seleccionRolControlador) {
        super();
        this.router = router;
        this.routerRolControlador = seleccionRolControlador;
        cargarImagenDesdeResources("7.jpg");
        initComponents();
        inicializarPantallas();
    }
    public PantallaAutenticacionVista(RouterControlador router) {
        this.router = router;
        initComponents();
        inicializarPantallas();
        
    }
    private void inicializarPantallas(){
        pantallasAutenticacion = new CardLayout();
        monitorAutenticacion.setLayout(pantallasAutenticacion);
        monitorAutenticacion.setVisible(false);
    }
    public void mostrarPanel(String nombrePanel) {
        pantallasAutenticacion.show(monitorAutenticacion, nombrePanel);
    }
    
    public void agregarPanel(JPanel panel, String nombre) {
        monitorAutenticacion.add(panel, nombre);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        monitorAutenticacion = new javax.swing.JPanel();
        panelRound1 = new com.panaderiamatemagica.autenticacion.vista.Clases.PanelRound();
        botonRegistrarse = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        botonIniciarSesion = new javax.swing.JButton();

        setBackground(new java.awt.Color(253, 188, 167));
        setForeground(new java.awt.Color(253, 188, 167));
        setPreferredSize(new java.awt.Dimension(833, 615));

        monitorAutenticacion.setBackground(new java.awt.Color(253, 188, 167));
        monitorAutenticacion.setPreferredSize(new java.awt.Dimension(596, 615));

        javax.swing.GroupLayout monitorAutenticacionLayout = new javax.swing.GroupLayout(monitorAutenticacion);
        monitorAutenticacion.setLayout(monitorAutenticacionLayout);
        monitorAutenticacionLayout.setHorizontalGroup(
            monitorAutenticacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );
        monitorAutenticacionLayout.setVerticalGroup(
            monitorAutenticacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        botonRegistrarse.setBackground(new java.awt.Color(84, 180, 183));
        botonRegistrarse.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonRegistrarse.setForeground(new java.awt.Color(0, 0, 0));
        botonRegistrarse.setText("Registrarse");
        botonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarseActionPerformed(evt);
            }
        });

        botonVolver.setBackground(new java.awt.Color(255, 51, 51));
        botonVolver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonVolver.setForeground(new java.awt.Color(0, 0, 0));
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        botonIniciarSesion.setBackground(new java.awt.Color(84, 180, 183));
        botonIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonIniciarSesion.setForeground(new java.awt.Color(0, 0, 0));
        botonIniciarSesion.setText("Iniciar Sesión");
        botonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(botonVolver))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(botonIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(botonRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(monitorAutenticacion, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(monitorAutenticacion, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(231, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarseActionPerformed
        routerRolControlador.mostrarRegistrarseVista();
        monitorAutenticacion.setVisible(true);
    }//GEN-LAST:event_botonRegistrarseActionPerformed

    private void botonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarSesionActionPerformed
        routerRolControlador.mostrarIniciarSesionVista();
        monitorAutenticacion.setVisible(true);
    }//GEN-LAST:event_botonIniciarSesionActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        router.mostrarSeleccionRolVista();
        monitorAutenticacion.setVisible(false);
    }//GEN-LAST:event_botonVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIniciarSesion;
    private javax.swing.JButton botonRegistrarse;
    private javax.swing.JButton botonVolver;
    private javax.swing.JPanel monitorAutenticacion;
    private com.panaderiamatemagica.autenticacion.vista.Clases.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables
}
