/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.panaderiamatemagica.autenticacion.vista;
import com.panaderiamatemagica.autenticacion.controlador.RouterRolControlador;
import com.panaderiamatemagica.comunes.RouterControlador;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author User
 */
public class PantallaAutenticacionVista extends javax.swing.JPanel {
    private RouterControlador router;
    private RouterRolControlador routerRolControlador;
    private CardLayout pantallasAutenticacion;
    
    public PantallaAutenticacionVista(RouterControlador router, RouterRolControlador seleccionRolControlador) {
        this.router = router;
        this.routerRolControlador = seleccionRolControlador;
        initComponents();
        inicializarPantallas();
    }
    public PantallaAutenticacionVista(RouterControlador router) {
        this.router = router;
        initComponents();
        inicializarPantallas();
        
    }
    private void inicializarPantallas(){
        pantallasAutenticacion = new CardLayout();
        monitorAutenticacion.setLayout(pantallasAutenticacion);
        monitorAutenticacion.setVisible(false);
    }
    public void mostrarPanel(String nombrePanel) {
        pantallasAutenticacion.show(monitorAutenticacion, nombrePanel);
    }
    
    public void agregarPanel(JPanel panel, String nombre) {
        monitorAutenticacion.add(panel, nombre);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonRegistrarse = new javax.swing.JButton();
        botonIniciarSesion = new javax.swing.JButton();
        monitorAutenticacion = new javax.swing.JPanel();
        botonVolver = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(833, 615));

        botonRegistrarse.setText("Registrarse");
        botonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarseActionPerformed(evt);
            }
        });

        botonIniciarSesion.setText("Iniciar Sesión");
        botonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarSesionActionPerformed(evt);
            }
        });

        monitorAutenticacion.setBackground(new java.awt.Color(102, 255, 255));
        monitorAutenticacion.setPreferredSize(new java.awt.Dimension(596, 615));

        javax.swing.GroupLayout monitorAutenticacionLayout = new javax.swing.GroupLayout(monitorAutenticacion);
        monitorAutenticacion.setLayout(monitorAutenticacionLayout);
        monitorAutenticacionLayout.setHorizontalGroup(
            monitorAutenticacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        monitorAutenticacionLayout.setVerticalGroup(
            monitorAutenticacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        botonVolver.setBackground(new java.awt.Color(255, 51, 51));
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonVolver)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(monitorAutenticacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(botonRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addComponent(botonIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(monitorAutenticacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarseActionPerformed
        routerRolControlador.mostrarRegistrarseVista();
        monitorAutenticacion.setVisible(true);
    }//GEN-LAST:event_botonRegistrarseActionPerformed

    private void botonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarSesionActionPerformed
        routerRolControlador.mostrarIniciarSesionVista();
        monitorAutenticacion.setVisible(true);
    }//GEN-LAST:event_botonIniciarSesionActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        router.mostrarSeleccionRolVista();
        monitorAutenticacion.setVisible(false);
    }//GEN-LAST:event_botonVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIniciarSesion;
    private javax.swing.JButton botonRegistrarse;
    private javax.swing.JButton botonVolver;
    private javax.swing.JPanel monitorAutenticacion;
    // End of variables declaration//GEN-END:variables
}
