/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.panaderiamatemagica.autenticacion.vista;
import com.panaderiamatemagica.autenticacion.controladores.alumnos.RouterAutenticacionControlador;
import com.panaderiamatemagica.core.visual.componentes.PanelConFondoVista;
import com.panaderiamatemagica.core.RouterControlador;
import com.panaderiamatemagica.core.visual.componentes.FondoPanel;
import java.awt.Color;
import javax.swing.JPanel;
import net.miginfocom.swing.MigLayout;
/**
 *
 * @author user
 */
public class SeleccionRolVista extends JPanel {
    private RouterControlador routerP;
    private RouterAutenticacionControlador routerA;
    
    public SeleccionRolVista(RouterControlador routerP, RouterAutenticacionControlador routerA) {
        super();
        initComponents();
        this.routerP = routerP;
        this.routerA = routerA;
        
        FondoPanel fondoPanel = new FondoPanel("Panel Ovalado.jpg");
        fondoPanel.setLayout(new MigLayout("fill, insets 0", "[grow]", "[grow]"));
    
    // Configurar MigLayout en este panel principal
    setLayout(new java.awt.BorderLayout());
    
    // Agregar el fondo primero
    add(fondoPanel, java.awt.BorderLayout.CENTER);
    

    
    // Remover componentes del diseño original
    remove(botonProfesor);
    remove(botonEstudiante);
    remove(titulo);
    // Agregar componentes al fondoPanel con posiciones específicas
    fondoPanel.add(botonProfesor, "pos 20% 20%, w 370:370:370, h 220:220:220");
    fondoPanel.add(botonEstudiante, "pos 20% 60%, w 370:370:370, h 220:220:220");
    fondoPanel.add(titulo, "pos 20% 5%, w 360:360:360, h 100:100:100");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        botonProfesor = new javax.swing.JButton();
        botonEstudiante = new javax.swing.JButton();

        setBackground(new java.awt.Color(213, 178, 137));
        setForeground(new java.awt.Color(255, 228, 171));
        setMinimumSize(new java.awt.Dimension(320, 440));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(640, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Showcard Gothic", 0, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("¿QUIEN ERES?");
        add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 360, 60));

        botonProfesor.setBackground(new java.awt.Color(117, 183, 168));
        botonProfesor.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        botonProfesor.setText("PROFESOR");
        botonProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonProfesorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonProfesorMouseExited(evt);
            }
        });
        add(botonProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 370, 220));

        botonEstudiante.setBackground(new java.awt.Color(117, 183, 168));
        botonEstudiante.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        botonEstudiante.setText("ESTUDIANTE");
        botonEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonEstudianteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonEstudianteMouseExited(evt);
            }
        });
        add(botonEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 370, 220));
    }// </editor-fold>//GEN-END:initComponents

    private void botonEstudianteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEstudianteMouseEntered
        botonEstudiante.setBackground(new Color(85, 208, 82));    }//GEN-LAST:event_botonEstudianteMouseEntered

    private void botonEstudianteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEstudianteMouseExited
        botonEstudiante.setBackground(new Color (117,183,168));
    }//GEN-LAST:event_botonEstudianteMouseExited

    private void botonProfesorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonProfesorMouseEntered
        botonProfesor.setBackground(new Color(85, 208, 82));                                                
    }//GEN-LAST:event_botonProfesorMouseEntered

    private void botonProfesorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonProfesorMouseExited
        botonProfesor.setBackground(new Color (117,183,168));
    }//GEN-LAST:event_botonProfesorMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEstudiante;
    private javax.swing.JButton botonProfesor;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
