/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.panaderiamatemagica.autenticacion.vista;

import com.panaderiamatemagica.autenticacion.controladores.alumnos.RouterAutenticacionControlador;
import com.panaderiamatemagica.core.visual.componentes.PanelConFondoVista;
import com.panaderiamatemagica.core.RouterControlador;
import com.panaderiamatemagica.core.visual.componentes.FondoPanel;
import com.panaderiamatemagica.core.visual.componentes.ResponsivePanel;
import com.panaderiamatemagica.core.visual.componentes.ScreenUtils;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.JPanel;
import javax.imageio.ImageIO;
import java.io.IOException;

/**
 *
 * @author user
 */
public class SeleccionRolVista extends JPanel {
    private RouterControlador routerP;
    private RouterAutenticacionControlador routerA;

    public SeleccionRolVista(RouterControlador routerP, RouterAutenticacionControlador routerA) {
        super();
        initComponents();
        aplicarReescaladoInterno();
        this.routerP = routerP;
        this.routerA = routerA;

        // Crear panel responsivo con dimensiones de diseño original
        ResponsivePanel responsivePanel = new ResponsivePanel(640, 660) {
            private Image backgroundImage;

            {
                try {
                    backgroundImage = ImageIO.read(getClass().getClassLoader().getResource("images/Panel Ovalado.jpg"));
                } catch (Exception e) {
                    System.err.println("Error cargando imagen de fondo: " + e.getMessage());
                }
            }

            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                if (backgroundImage != null) {
                    g.drawImage(backgroundImage, 0, 0, getWidth(), getHeight(), this);
                }
            }
        };

        // Configurar layout principal
        setLayout(new java.awt.BorderLayout());
        add(responsivePanel, java.awt.BorderLayout.CENTER);

        // Remover componentes del diseño original
        remove(botonProfesor);
        remove(botonEstudiante);
        remove(titulo);

        // Agregar componentes al panel responsivo con posiciones originales
        responsivePanel.addScalable(titulo, 130, 40, 360, 100);
        responsivePanel.addScalable(botonEstudiante, 140, 150, 370, 220);
        responsivePanel.addScalable(botonProfesor, 140, 400, 370, 220);
    }
        private void aplicarReescaladoInterno() {
        double scaleFactor = ScreenUtils.getScaleFactor();
        
        // Solo aplicar si el factor es significativamente diferente a 1
        if (Math.abs(scaleFactor - 1.0) > 0.01) {
            
            // Reescalar recursivamente a todos los elementos dentro de ESTE PANEL
            ScreenUtils.scaleComponentRecursively(this, scaleFactor);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: DO NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        botonProfesor = new javax.swing.JButton();
        botonEstudiante = new javax.swing.JButton();

        setBackground(new java.awt.Color(213, 178, 137));
        setForeground(new java.awt.Color(255, 228, 171));
        setMinimumSize(new java.awt.Dimension(320, 440));
        setPreferredSize(new java.awt.Dimension(640, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("¿QUIÉN ERES?");
        add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 360, 60));

        botonProfesor.setBackground(new java.awt.Color(117, 183, 168));
        botonProfesor.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        botonProfesor.setForeground(new java.awt.Color(255, 255, 255));
        botonProfesor.setText("PROFESOR");
        botonProfesor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonProfesorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonProfesorMouseExited(evt);
            }
        });
        botonProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProfesorActionPerformed(evt);
            }
        });
        add(botonProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 370, 220));

        botonEstudiante.setBackground(new java.awt.Color(117, 183, 168));
        botonEstudiante.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        botonEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        botonEstudiante.setText("ESTUDIANTE");
        botonEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonEstudianteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonEstudianteMouseExited(evt);
            }
        });
        botonEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEstudianteActionPerformed(evt);
            }
        });
        add(botonEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 370, 220));
    }// </editor-fold>//GEN-END:initComponents

    private void botonProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProfesorActionPerformed
        routerA.mostrarInicioSesionAdminVista();
    }//GEN-LAST:event_botonProfesorActionPerformed

    private void botonEstudianteMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_botonEstudianteMouseEntered
        botonEstudiante.setBackground(new Color(85, 208, 82));
    }// GEN-LAST:event_botonEstudianteMouseEntered

    private void botonEstudianteMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_botonEstudianteMouseExited
        botonEstudiante.setBackground(new Color(117, 183, 168));
    }// GEN-LAST:event_botonEstudianteMouseExited

    private void botonProfesorMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_botonProfesorMouseEntered
        botonProfesor.setBackground(new Color(85, 208, 82));
    }// GEN-LAST:event_botonProfesorMouseEntered

    private void botonProfesorMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_botonProfesorMouseExited
        botonProfesor.setBackground(new Color(117, 183, 168));
    }// GEN-LAST:event_botonProfesorMouseExited

    private void botonEstudianteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botonEstudianteActionPerformed
        routerA.mostrarIniciarSesion();
    }// GEN-LAST:event_botonEstudianteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEstudiante;
    private javax.swing.JButton botonProfesor;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
