/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.panaderiamatemagica.admin.vista;


import com.panaderiamatemagica.autenticacion.controladores.administradores.AdministradorControladorCrearAdmin;
import com.panaderiamatemagica.core.RouterControlador;
import javax.swing.JTextField;

/**
 *
 * @author User
 */
public class CrearNuevoAdminVista extends javax.swing.JPanel {
    
    private AdministradorControladorCrearAdmin controlador;
    
    /**
     * Creates new form CrearNuevoAdminVIsta
     * @param router
     */
    public CrearNuevoAdminVista(RouterControlador router) {
        
        // inicializamos el controlador
        controlador = new AdministradorControladorCrearAdmin(this
                ,router.getListaProfesores());
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtcontrasenna = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 153));
        setPreferredSize(new java.awt.Dimension(555, 615));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(84, 180, 183));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("CREAR ADMINISTRADOR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 420, 170));

        txtcontrasenna.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        add(txtcontrasenna, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 470, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CONTRASEÑA");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 350, 150));

        txtusuario.setBackground(new java.awt.Color(255, 255, 255));
        txtusuario.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 460, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USUARIO");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 280, 150));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("CREAR NUEVO ADMINISTRADOR");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 500, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // bonto de registro de nuevo admin
        controlador.crearAdministrador();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    //get usuario y contraseña
    public String getTxtcontrasenna() {
        return txtcontrasenna.getText();
    }
    public String getTxtusuario() {
        return txtusuario.getText();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtcontrasenna;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
