/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.panaderiamatemagica.autenticacion.vista;

import com.panaderiamatemagica.autenticacion.controladores.alumnos.AlumnoControladorRegistro;
import com.panaderiamatemagica.autenticacion.modelo.AlumnoModelo;
import com.panaderiamatemagica.core.RouterControlador;
import javax.swing.JLabel;
import java.awt.Color;
import java.awt.Font;
/**
 *
 * @author user
 */
public class RegistroVista extends javax.swing.JPanel {
    
    //Estos son los labels que hay que implementar, ya hice todas las funciones pero no se como implementar los jlabel en el panel:v
    private JLabel lblErrorNombre;
    private JLabel lblErrorApellido;
    private JLabel lblErrorApodo;
    private JLabel lblErrorFechaNacimiento;
    
    // Las variables: router, nuevoAlumno y objetoControlador estaban duplicadas
    // en tu código. Dejo solo una declaración de cada una aquí.
    private RouterControlador router;
    private AlumnoModelo nuevoAlumno;
    private AlumnoControladorRegistro objetoControlador;
    
    // Las variables generadas por el IDE (jButton1, jTextField1, etc.)
    // no se declaran aquí, se declaran únicamente al final en la sección "do not modify".
    
    /**
     * Creates new form RegistroVista
     */
    public RegistroVista(RouterControlador router) {
        this.router = router;
        
        lblErrorNombre = crearLabelError();
        lblErrorApellido = crearLabelError();
        lblErrorApodo = crearLabelError();
        lblErrorFechaNacimiento = crearLabelError();

        this.add(lblErrorNombre);
        this.add(lblErrorApellido);
        this.add(lblErrorApodo);
        this.add(lblErrorFechaNacimiento);

        // creamos el alumno
        nuevoAlumno = new AlumnoModelo(); 

        // creamos el controlador (CON DOS PARÁMETROS)
        objetoControlador = new AlumnoControladorRegistro(
            nuevoAlumno,
            this
        );
        initComponents();
    }
    
    private JLabel crearLabelError() {
        JLabel label = new JLabel("");
        label.setForeground(Color.RED); 
        label.setFont(new Font("Segoe UI", Font.ITALIC, 11)); 
        label.setVisible(false); // Oculto por defecto
        return label;
    }
    
    public void mostrarErrorNombre(String mensaje) {
        lblErrorNombre.setText("" + mensaje);
        lblErrorNombre.setVisible(true);
    }
    public void limpiarErrorNombre() {
        lblErrorNombre.setText("");
        lblErrorNombre.setVisible(false);
    }
    public void mostrarErrorApellido(String mensaje) {
        lblErrorApellido.setText("" + mensaje);
        lblErrorApellido.setVisible(true);
    }
    public void limpiarErrorApellido() {
        lblErrorApellido.setText("");
        lblErrorApellido.setVisible(false);
    }
    public void mostrarErrorApodo(String mensaje) {
        lblErrorApodo.setText("" + mensaje);
        lblErrorApodo.setVisible(true);
    }
    public void limpiarErrorApodo() {
        lblErrorApodo.setText("");
        lblErrorApodo.setVisible(false);
    }
    public void mostrarErrorFechaNacimiento(String mensaje) {
        lblErrorFechaNacimiento.setText("" + mensaje);
        lblErrorFechaNacimiento.setVisible(true);
    }
    public void limpiarErrorFechaNacimiento() {
        lblErrorFechaNacimiento.setText("");
        lblErrorFechaNacimiento.setVisible(false);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        txtnombre = new javax.swing.JLabel();
        txtapellido = new javax.swing.JLabel();
        txtapodo = new javax.swing.JLabel();
        txtfechaNacimiento = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(253, 188, 167));
        setPreferredSize(new java.awt.Dimension(596, 615));

        txtnombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtnombre.setText("Nombre");

        txtapellido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtapellido.setText("Apellido");

        txtapodo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtapodo.setText("Apodo");

        txtfechaNacimiento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtfechaNacimiento.setText("Fecha de nacimiento");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(84, 180, 183));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("REGISTRARSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtfechaNacimiento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtapodo)
                                .addGap(52, 52, 52))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(txtnombre)))
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtapellido)
                                .addGap(49, 49, 49)))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombre)
                    .addComponent(txtapellido))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfechaNacimiento)
                    .addComponent(txtapodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(192, 192, 192)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>                        

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    try {
            if (objetoControlador.validarDatos()) {
                // Solo si la validacion es exitosa y el registro fue guardado:
                router.mostrarSeleccionPanaderoVista(); 
            }
        } catch (java.sql.SQLException e) {
            // muy loco.
            System.err.println("ERROR: Fallo de base de datos durante el registro: " + e.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error de conexión o consulta a la Base de Datos. Verifique su coneccion wifi .",
                ">>", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }                                        

    // get de los paramentros.
    public String getTxtapellido() {
        return jTextField3.getText();
    }
    public String getTxtnombre() {
        return jTextField1.getText();
    }
    public String getTxtapodo() {
        return jTextField5.getText();
    }
    public String getTxtfechaNacimiento() {
        return jTextField4.getText(); 
    }
       
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel txtapellido;
    private javax.swing.JLabel txtapodo;
    private javax.swing.JLabel txtfechaNacimiento;
    private javax.swing.JLabel txtnombre;
    // End of variables declaration                   
}
