/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.panaderiamatemagica.juego.vista;

import com.panaderiamatemagica.core.RouterControlador;
import com.panaderiamatemagica.core.visual.componentes.FondoPanel;
import com.panaderiamatemagica.ejercicios.controlador.EjercicioControladorVista;
import com.panaderiamatemagica.ejercicios.modelo.EjercicioModelo;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author User
 */
public class EjercicioVista extends javax.swing.JPanel {
    private RouterControlador router;
    private EjercicioControladorVista controlador;

    public EjercicioVista(RouterControlador router) {
        this.router = router;
        // El controlador de ejercicios se inicializa con el router y una referencia a
        // esta vista.
        this.controlador = new EjercicioControladorVista(router, this);
        initComponents();
        
        FondoPanel fondoPanel = new FondoPanel("fondoAzulProfundo.png");
    fondoPanel.setLayout(new MigLayout("fill, insets 0", "[grow]", "[grow]"));
    
    // Configurar MigLayout en este panel principal
    setLayout(new java.awt.BorderLayout());
    
    // Agregar el fondo primero
    add(fondoPanel, java.awt.BorderLayout.CENTER);
    
    // Remover componentes del diseño original
    remove(fondo);
    remove(b1);
    remove(b2);
    remove(b3);
    remove(b4);
    remove(label1);
    remove(label2);
    
    // Agregar componentes al fondoPanel con posiciones específicas
    fondoPanel.add(b1, "pos 4.8% 56.91%, w 773:773:773, h 100:100:100");
    fondoPanel.add(b2,"pos 4.8% 78%, w 773:773:773, h 100:100:100");
    fondoPanel.add(b3,"pos 75% 57%, w 773:773:773, h 100:100:100");
    fondoPanel.add(b4,"pos 75% 78%, w 773:773:773, h 100:100:100");
    fondoPanel.add(label1,"pos 25% 12.68%, w 773:773:773, h 38:38:38");
    fondoPanel.add(label2,"pos 25% 19.84%, w 773:773:773, h 38:38:38");
    }

    // segun la metodoligia mvc esta bien colocar la funcion aqui.(tengo entendido).
    public void cargarEjercicio(EjercicioModelo ejercicio) {

        // 1. Actualizar el texto de la pregunta y descripción
        label1.setText(ejercicio.getPregunta());
        label2.setText(ejercicio.getDescripcion());

        // 2. Actualizar el texto de los botones de respuesta
        ArrayList<String> opciones = ejercicio.getOpcionesRespuestas();

        if (opciones != null && opciones.size() >= 4) {
            b1.setText(opciones.get(0));
            b2.setText(opciones.get(1));
            b3.setText(opciones.get(2));
            b4.setText(opciones.get(3));
        } else {
            JOptionPane.showMessageDialog(this,
                    "El ejercico esta loco. Revisar la carga",
                    "ver: bien..", JOptionPane.ERROR_MESSAGE);
        }
    }

    // METODO AGREGADO: Implementacion correcta de la interfaz con el Router
    public void iniciarNuevoNivel() {
        // Llama al método clave en tu controlador.
        if (controlador != null) {
            controlador.iniciarNuevoNivel();
        }
    }

    /**
     * Actualiza la visualización de vidas restantes
     * 
     * @param vidas Número de vidas restantes (0-5)
     */
    public void actualizarVidas(int vidas) {
        // Actualizar la barra de progreso para mostrar vidas
        // 5 vidas = 100%, 0 vidas = 0%
        int porcentaje = (vidas * 100) / 5;
        jProgressBar1.setValue(porcentaje);

        // Cambiar color según las vidas
        if (vidas >= 4) {
            jProgressBar1.setForeground(new java.awt.Color(0, 200, 0)); // Verde
        } else if (vidas >= 2) {
            jProgressBar1.setForeground(new java.awt.Color(255, 200, 0)); // Amarillo
        } else {
            jProgressBar1.setForeground(new java.awt.Color(255, 0, 0)); // Rojo
        }

        // Opcional: Actualizar un label con el texto
        jProgressBar1.setString("❤ Vidas: " + vidas + "/5");
        jProgressBar1.setStringPainted(true);
    }

    /**
     * Obtiene el controlador de ejercicios
     */
    public EjercicioControladorVista getControlador() {
        return controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new javax.swing.JLabel();
        b3 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        label2 = new javax.swing.JLabel();
        fondo = new com.panaderiamatemagica.core.visual.componentes.JLabelReescalable();
        jProgressBar1 = new javax.swing.JProgressBar();

        setBackground(new java.awt.Color(255, 228, 196));
        setPreferredSize(new java.awt.Dimension(833, 615));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("PREGUNTA");
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 78, 773, 38));

        b3.setBackground(new java.awt.Color(0, 204, 0));
        b3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        b3.setForeground(new java.awt.Color(0, 0, 0));
        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 301, 100));

        b2.setBackground(new java.awt.Color(255, 64, 163));
        b2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        b2.setForeground(new java.awt.Color(0, 0, 0));
        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 301, 100));

        b4.setBackground(new java.awt.Color(204, 0, 204));
        b4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        b4.setForeground(new java.awt.Color(0, 0, 0));
        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, 301, 100));

        b1.setBackground(new java.awt.Color(73, 73, 230));
        b1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        b1.setForeground(new java.awt.Color(0, 0, 0));
        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 301, 100));

        label2.setBackground(new java.awt.Color(255, 255, 255));
        label2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label2.setText("Descripción");
        add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 122, 773, 28));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoAzulProfundo.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 670));
        add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 580, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtrespuesta1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtrespuesta1ActionPerformed
        String respuestaElegida = b1.getText(); // Obtener el texto del botón
        if (controlador != null) {
            controlador.validarRespuesta(respuestaElegida);
        }
    }// GEN-LAST:event_txtrespuesta1ActionPerformed

    private void txtrespuesta2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtrespuesta2ActionPerformed
        String respuestaElegida = b2.getText();
        if (controlador != null) {
            controlador.validarRespuesta(respuestaElegida);
        }
    }// GEN-LAST:event_txtrespuesta2ActionPerformed

    private void txtrespuesta3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtrespuesta3ActionPerformed
        String respuestaElegida = b3.getText();
        if (controlador != null) {
            controlador.validarRespuesta(respuestaElegida);
        }
    }// GEN-LAST:event_txtrespuesta3ActionPerformed

    private void txtxrespuesta4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtxrespuesta4ActionPerformed
        String respuestaElegida = b4.getText();
        if (controlador != null) {
            controlador.validarRespuesta(respuestaElegida);
        }
    }// GEN-LAST:event_txtxrespuesta4ActionPerformed
    
    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
// Nivel 1 corresponde al indice 0 de la lista de niveles
    String respuestaElegida = b1.getText(); // Obtener el texto del botón
        if (controlador != null) {
            controlador.validarRespuesta(respuestaElegida);
    }
    }

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {                                   
    // nivel 2
        String respuestaElegida = b2.getText();
        if (controlador != null) {
            controlador.validarRespuesta(respuestaElegida);
        }
    }                                  

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // nivel 3
        String respuestaElegida = b3.getText();
        if (controlador != null) {
            controlador.validarRespuesta(respuestaElegida);
        }
         
    }           
    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // nivel 3
        String respuestaElegida = b4.getText();
        if (controlador != null) {
            controlador.validarRespuesta(respuestaElegida);
        }
    }         
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private com.panaderiamatemagica.core.visual.componentes.JLabelReescalable fondo;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    // End of variables declaration//GEN-END:variables
}
