/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.panaderiamatemagica.juego.vista;

import com.panaderiamatemagica.core.RouterControlador;
import com.panaderiamatemagica.core.visual.componentes.FondoPanel;
import com.panaderiamatemagica.core.visual.componentes.ScreenUtils;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author User
 */
public class ResultadoVista extends javax.swing.JPanel {
    private RouterControlador router;
    private FondoPanel fondoPanel;
    /**
     * Creates new form ResultadoVista
     */
    public ResultadoVista(RouterControlador router) {
        this.router = router;
        initComponents();
        aplicarReescaladoInterno();
         fondoPanel = new FondoPanel("resultados.jpg");
    fondoPanel.setLayout(new MigLayout("fill, insets 0", "[grow]", "[grow]"));
    
    // Configurar MigLayout en este panel principal
    setLayout(new java.awt.BorderLayout());
    
    // Agregar el fondo primero
    add(fondoPanel, java.awt.BorderLayout.CENTER);
    
    // Remover componentes del diseño original
    remove(jButton1);
    
    fondoPanel.add(jButton1, "pos 20% 83.50%, w 300:300:300, h 65:65:65");
    fondoPanel.add(jButton2, "pos 40% 83.50%, w 300:300:300, h 65:65:65");
    fondoPanel.add(jButton3, "pos 60% 83.50%, w 300:300:300, h 65:65:65");
    fondoPanel.add(jLabel1, "pos 40.42% 62.79%, w 600:600:600, h 50:50:50");
    fondoPanel.add(jPanel1, "pos 42.42% 25.02%, w 220:220:220, h 230:230:230");
    }

    private void aplicarReescaladoInterno() {
        double scaleFactor = ScreenUtils.getScaleFactor();
        
        // Solo aplicar si el factor es significativamente diferente a 1
        if (Math.abs(scaleFactor - 1.0) > 0.01) {
            
            // Reescalar recursivamente a todos los elementos dentro de ESTE PANEL
            ScreenUtils.scaleComponentRecursively(this, scaleFactor);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelReescalable1 = new com.panaderiamatemagica.core.visual.componentes.JLabelReescalable();

        setBackground(new java.awt.Color(255, 204, 204));
        setPreferredSize(new java.awt.Dimension(833, 615));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(204, 153, 0));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("REGRESAR A SELECCION DE DIMENSION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, 190, 40));

        jButton2.setBackground(new java.awt.Color(255, 255, 51));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("REPETIR NIVEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, 190, 40));

        jButton3.setBackground(new java.awt.Color(0, 255, 0));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("SIGUIENTE NIVEL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 170, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 56)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¡LO LOGRASTE!");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 380, 50));

        jPanel1.setBackground(new java.awt.Color(255, 228, 196));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 330, 130));

        jLabelReescalable1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resultados.jpg"))); // NOI18N
        jLabelReescalable1.setText("jLabelReescalable1");
        add(jLabelReescalable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        router.mostrarSeleccionDimension1();
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        // Repetir nivel - reiniciar el nivel actual
        EjercicioVista ejercicioVista = router.getPantallaEjercicio();
        if (ejercicioVista != null) {
            ejercicioVista.iniciarNuevoNivel();
            router.mostrarEjercicioVista();
        }
    }// GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
        // Siguiente nivel - por ahora regresa a selección de dimensión
        // TODO: Implementar lógica para cargar el siguiente nivel automáticamente
        router.mostrarSeleccionDimension1();
    }// GEN-LAST:event_jButton3ActionPerformed

    /**
     * Muestra los resultados del nivel completado
     * 
     * @param estrellas      Número de estrellas obtenidas (0-3)
     * @param galletas       Cantidad de galletas ganadas
     * @param aciertos       Número de respuestas correctas
     * @param desaciertos    Número de respuestas incorrectas
     * @param vidasRestantes Vidas que quedaron
     */
    public void mostrarResultados(int estrellas, int galletas, int aciertos, int desaciertos, int vidasRestantes) {
        // Actualizar estrellas visuales
        String estrellasTexto = "";
        for (int i = 0; i < 3; i++) {
            if (i < estrellas) {
                estrellasTexto += "⭐ ";
            } else {
                estrellasTexto += "☆ ";
            }
        }

        jLabel1.setText(estrellasTexto);

        // Actualizar mensaje según estrellas
        if (estrellas == 3) {
            jLabel1.setText("¡PERFECTO! ¡MAESTRO PANADERO!");
            jLabel1.setForeground(new java.awt.Color(0, 255, 0)); // Dorado
            jLabel1.setFont(jLabel1.getFont().deriveFont(30f));
            
            remove(jPanel1);
            fondoPanel.add(jPanel1, "pos 42.42% 25.02%, w 0:0:0, h 230:230:230");
        } else if (estrellas == 2) {
            jLabel1.setText("¡MUY BIEN! ¡Sigue así!");
            jLabel1.setForeground(new java.awt.Color(192, 192, 192)); // Plateado
            jLabel1.setFont(jLabel1.getFont().deriveFont(30f));
            
            remove(jPanel1);
            fondoPanel.add(jPanel1, "pos 42.42% 25.02%, w 220:220:220, h 230:230:230");
            
        } else if (estrellas == 1) {
            jLabel1.setText("¡BUEN INTENTO! Puedes mejorar");
            jLabel1.setForeground(new java.awt.Color(205, 127, 50)); // Bronce
            jLabel1.setFont(jLabel1.getFont().deriveFont(30f));
            
            remove(jPanel1);
            fondoPanel.add(jPanel1, "pos 42.42% 25.02%, w 450:450:450, h 230:230:230");
        } else {
            jLabel1.setText("INTÉNTALO DE NUEVO");
            jLabel1.setForeground(new java.awt.Color(255, 0, 0)); // Rojo
            jLabel1.setFont(jLabel1.getFont().deriveFont(40f));
            
            remove(jPanel1);
            fondoPanel.add(jPanel1, "pos 42.42% 25.02%, w 650:650:650, h 230:230:230");
        }

        // Deshabilitar botón "Siguiente Nivel" si no obtuvo al menos 1 estrella
        if (estrellas < 1) {
            jButton3.setEnabled(false);
            jButton3.setBackground(new java.awt.Color(150, 150, 150));
            jButton3.setText("NIVEL BLOQUEADO");
        } else {
            jButton3.setEnabled(true);
            jButton3.setBackground(new java.awt.Color(0, 255, 0));
            jButton3.setText("SIGUIENTE NIVEL");
        }
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private com.panaderiamatemagica.core.visual.componentes.JLabelReescalable jLabelReescalable1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
