/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.panaderiamatemagica.juego.vista;

/**
 *
 * @author User
 */
public class SeleccionDimensionVista1 extends javax.swing.JPanel {

    /**
     * Creates new form SeleccionDimensionVista1
     */
    public SeleccionDimensionVista1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();

        setPreferredSize(new java.awt.Dimension(833, 615));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(jRadioButton1);
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 427, -1, -1));

        buttonGroup1.add(jRadioButton2);
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, -1, -1));

        buttonGroup1.add(jRadioButton3);
        add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, -1));

        buttonGroup1.add(jRadioButton4);
        add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, -1, -1));

        buttonGroup1.add(jRadioButton5);
        add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    // End of variables declaration//GEN-END:variables
}
