/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.panaderiamatemagica.juego.vista;

import com.panaderiamatemagica.core.RouterControlador;
import com.panaderiamatemagica.core.visual.componentes.FondoPanel;
import javax.swing.ButtonModel;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author User
 */
public class SeleccionDimensionVista1 extends javax.swing.JPanel {
    private RouterControlador router;
    /**
     * Creates new form SeleccionDimensionVista1
     */
    public SeleccionDimensionVista1(RouterControlador router) {
        this.router = router;
        initComponents();
    FondoPanel fondoPanel = new FondoPanel("fondoSeleccionDimension.png");
    fondoPanel.setLayout(new MigLayout("fill, insets 0", "[grow]", "[grow]"));
    
    // Configurar MigLayout en este panel principal
    setLayout(new java.awt.BorderLayout());
    
    // Agregar el fondo primero
    add(fondoPanel, java.awt.BorderLayout.CENTER);
        
    remove(d1);
    remove(d2);
    remove(d3);
    remove(d4);
    remove(d5);
    
    remove(boton);
    remove(volver);
    
    remove(fondo);
    
    remove(arena);
    remove(arepa);
    
    remove(rosca);
    remove(rocosa);
    
    remove(torbellino);
    remove(tequeño);
    
    remove(cancha);
    remove(concha);
    
    remove(pradera);
    remove(palmera);
    
    remove(titulo);
    
    fondoPanel.add(d1, "pos 25% 67.80% , w 40:40:40 , h 30:30:30");
    fondoPanel.add(d2, "pos 39% 68.29% , w 40:40:40 , h 30:30:30");
    fondoPanel.add(d3, "pos 50% 68.29% , w 40:40:40 , h 30:30:30");
    fondoPanel.add(d4, "pos 61% 68.29% , w 40:40:40 , h 30:30:30");
    fondoPanel.add(d5, "pos 71% 68.29% , w 40:40:40 , h 30:30:30");
    
    fondoPanel.add(boton, "pos 40% 82.93%, w 290:290:290 , h 70:70:70");
    fondoPanel.add(volver, "pos 86% 84%, w 80:80:80, h 60:60:60");
    
    fondoPanel.add(arena , "pos  22.1% 68.29%, w 100:100:100 , h 60:60:60");
    fondoPanel.add(arepa , "pos  22.1% 71.54% , w 100:100:100 , h 60:60:60");
    
    fondoPanel.add(rosca , "pos 34.81% 68.29% , w 100:100:100 , h 60:60:60");
    fondoPanel.add(rocosa , "pos 36.3% 71.54% , w 100:100:100 , h 60:60:60");
    
    fondoPanel.add(torbellino , "pos 47% 68.29% , w 100:100:100 , h 60:60:60");
    fondoPanel.add(tequeño , "pos 47.8% 71.54% , w 100:100:100 , h 60:60:60");
    
    fondoPanel.add(cancha , "pos 58.22% 68.29% , w 100:100:100 , h 60:60:60");
    fondoPanel.add(concha , "pos 58.22% 71.54% , w 100:100:100 , h 60:60:60");
    
    fondoPanel.add(pradera , "pos 68.1% 68.29% , w 100:100:100 , h 60:60:60");
    fondoPanel.add(palmera , "pos 68.1% 71.54% , w 100:100:100 , h 60:60:60");
    
    fondoPanel.add(titulo, "pos 30.80% 29.27%, w 590:590:590, h 60:60:60");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        d1 = new javax.swing.JRadioButton();
        d3 = new javax.swing.JRadioButton();
        d2 = new javax.swing.JRadioButton();
        d4 = new javax.swing.JRadioButton();
        d5 = new javax.swing.JRadioButton();
        boton = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        cancha = new javax.swing.JLabel();
        arepa = new javax.swing.JLabel();
        arena = new javax.swing.JLabel();
        rosca = new javax.swing.JLabel();
        tequeño = new javax.swing.JLabel();
        rocosa = new javax.swing.JLabel();
        pradera = new javax.swing.JLabel();
        torbellino = new javax.swing.JLabel();
        palmera = new javax.swing.JLabel();
        concha = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        fondo = new com.panaderiamatemagica.core.visual.componentes.JLabelReescalable();

        setPreferredSize(new java.awt.Dimension(833, 615));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(d1);
        d1.setForeground(new java.awt.Color(255, 255, 255));
        d1.setActionCommand("d1");
        d1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        d1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deseleccionado.png"))); // NOI18N
        d1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seleccionado.png"))); // NOI18N
        add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 20, 30));

        buttonGroup1.add(d3);
        d3.setActionCommand("d3");
        d3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deseleccionado.png"))); // NOI18N
        d3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seleccionado.png"))); // NOI18N
        add(d3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 20, 30));

        buttonGroup1.add(d2);
        d2.setActionCommand("d2");
        d2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deseleccionado.png"))); // NOI18N
        d2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seleccionado.png"))); // NOI18N
        add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 20, 30));

        buttonGroup1.add(d4);
        d4.setActionCommand("d4");
        d4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deseleccionado.png"))); // NOI18N
        d4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seleccionado.png"))); // NOI18N
        add(d4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 20, 30));

        buttonGroup1.add(d5);
        d5.setActionCommand("d5");
        d5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deseleccionado.png"))); // NOI18N
        d5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seleccionado.png"))); // NOI18N
        add(d5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, 30, 30));

        boton.setBackground(new java.awt.Color(51, 255, 51));
        boton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        boton.setForeground(new java.awt.Color(0, 0, 0));
        boton.setText("CONTINUAR");
        boton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });
        boton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botonKeyPressed(evt);
            }
        });
        add(boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 290, 70));

        volver.setBackground(new java.awt.Color(255, 0, 0));
        volver.setText("VOLVER");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, 80, 60));

        cancha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancha.setForeground(new java.awt.Color(0, 0, 0));
        cancha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancha.setText("Cancha");
        add(cancha, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 100, 60));

        arepa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        arepa.setForeground(new java.awt.Color(0, 0, 0));
        arepa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arepa.setText("Arepa");
        add(arepa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 60, 60));

        arena.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        arena.setForeground(new java.awt.Color(0, 0, 0));
        arena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arena.setText("Arena");
        add(arena, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 60, 60));

        rosca.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rosca.setForeground(new java.awt.Color(0, 0, 0));
        rosca.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rosca.setText("Rosca");
        add(rosca, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 60, 60));

        tequeño.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tequeño.setForeground(new java.awt.Color(0, 0, 0));
        tequeño.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tequeño.setText("Tequeño");
        add(tequeño, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 90, 60));

        rocosa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rocosa.setForeground(new java.awt.Color(0, 0, 0));
        rocosa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rocosa.setText("Rocosa");
        add(rocosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 70, 60));

        pradera.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pradera.setForeground(new java.awt.Color(0, 0, 0));
        pradera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pradera.setText("Pradera");
        add(pradera, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 100, 60));

        torbellino.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        torbellino.setForeground(new java.awt.Color(0, 0, 0));
        torbellino.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        torbellino.setText("Torbellino");
        add(torbellino, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 100, 60));

        palmera.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        palmera.setForeground(new java.awt.Color(0, 0, 0));
        palmera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palmera.setText("Palmera");
        add(palmera, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 100, 60));

        concha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        concha.setForeground(new java.awt.Color(0, 0, 0));
        concha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        concha.setText("Concha");
        add(concha, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 100, 60));

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("SELECCIONA TU DIMENSIÓN");
        add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 590, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoSeleccionDimension.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        router.mostrarFondoAutenticacionVista();
    }//GEN-LAST:event_volverActionPerformed

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
        // 1. Obtener el modelo de selección
    ButtonModel modeloSeleccionado = buttonGroup1.getSelection();

    if (modeloSeleccionado != null) {
        
        // 2. Obtener el comando de acción (el String que configuraste en las propiedades)
        String comando = modeloSeleccionado.getActionCommand();

        // 3. Usar un Switch para ejecutar la lógica correspondiente
        switch (comando) {
            case "d1":
                // Lógica o llamada a método para Opción A
                router.mostrarDimension1Vista();
                break;
            case "d2":
                router.mostrarDimension2Vista();
                
                break;
            case "d3":
                router.mostrarDimension3Vista();
                
                break;
            case "d4":
                router.mostrarDimension4Vista();
                
                break;
            case "d5":
                router.mostrarDimension5Vista();
                
                break;
            default:
                
                break;
        }
    } 

    }//GEN-LAST:event_botonActionPerformed

    private void botonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arena;
    private javax.swing.JLabel arepa;
    private javax.swing.JButton boton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cancha;
    private javax.swing.JLabel concha;
    private javax.swing.JRadioButton d1;
    private javax.swing.JRadioButton d2;
    private javax.swing.JRadioButton d3;
    private javax.swing.JRadioButton d4;
    private javax.swing.JRadioButton d5;
    private com.panaderiamatemagica.core.visual.componentes.JLabelReescalable fondo;
    private javax.swing.JLabel palmera;
    private javax.swing.JLabel pradera;
    private javax.swing.JLabel rocosa;
    private javax.swing.JLabel rosca;
    private javax.swing.JLabel tequeño;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel torbellino;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
