/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.panaderiamatemagica.juego.vista;

import com.panaderiamatemagica.comunes.RouterControlador;
import com.panaderiamatemagica.juego.controlador.RouterDimensionControlador;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class SeleccionDimensionVista extends javax.swing.JPanel {
    private CardLayout pantallasDimensiones;
    private RouterDimensionControlador routerDimension;
    private RouterControlador router;
    /**
     * Creates new form SeleccionDimensionVista
     */
    public SeleccionDimensionVista(RouterControlador router, RouterDimensionControlador routerDimension) {
        initComponents();
        this.router = router;
        this.routerDimension = routerDimension;
        inicializarPantallas();
    }
    
    private void inicializarPantallas(){
    pantallasDimensiones = new CardLayout();
    monitorDimensiones.setLayout(pantallasDimensiones);
    monitorDimensiones.setVisible(false);
}

    public void mostrarPanel(String nombrePanel) {
        pantallasDimensiones.show(monitorDimensiones, nombrePanel);
    }
    
    public void agregarPanel(JPanel panel, String nombre) {
        monitorDimensiones.add(panel, nombre);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dimencion2 = new javax.swing.JButton();
        dimencion1 = new javax.swing.JButton();
        dimencion3 = new javax.swing.JButton();
        dimencio4 = new javax.swing.JButton();
        dimencion5 = new javax.swing.JButton();
        pruebaDiagnostica = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        monitorDimensiones = new javax.swing.JPanel();

        setBackground(new java.awt.Color(204, 153, 255));
        setPreferredSize(new java.awt.Dimension(833, 615));

        dimencion2.setText("2° DIMENSION");
        dimencion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dimencion2ActionPerformed(evt);
            }
        });

        dimencion1.setText("1° DIMENSION");
        dimencion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dimencion1ActionPerformed(evt);
            }
        });

        dimencion3.setText("3° DIMENSION");
        dimencion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dimencion3ActionPerformed(evt);
            }
        });

        dimencio4.setText("4° DIMENSION");
        dimencio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dimencio4ActionPerformed(evt);
            }
        });

        dimencion5.setText("5° DIMENSION");
        dimencion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dimencion5ActionPerformed(evt);
            }
        });

        pruebaDiagnostica.setText("PRUEBA DIAGNOSTICA");
        pruebaDiagnostica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pruebaDiagnosticaActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 0, 0));
        jButton7.setText("VOLVER");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        monitorDimensiones.setBackground(new java.awt.Color(255, 153, 255));
        monitorDimensiones.setPreferredSize(new java.awt.Dimension(612, 615));

        javax.swing.GroupLayout monitorDimensionesLayout = new javax.swing.GroupLayout(monitorDimensiones);
        monitorDimensiones.setLayout(monitorDimensionesLayout);
        monitorDimensionesLayout.setHorizontalGroup(
            monitorDimensionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );
        monitorDimensionesLayout.setVerticalGroup(
            monitorDimensionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pruebaDiagnostica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dimencio4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dimencion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dimencion2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dimencion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dimencion5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton7)))
                .addGap(18, 18, 18)
                .addComponent(monitorDimensiones, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(dimencion1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dimencion2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dimencion3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(dimencio4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(dimencion5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(pruebaDiagnostica, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(monitorDimensiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dimencion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dimencion1ActionPerformed
        // Llama al RouterControlador principal para que él se encargue de la inicialización
        // y luego muestre la vista. Esto previene la NullPointerException.
        router.iniciarDimension1();
        monitorDimensiones.setVisible(true);
    }//GEN-LAST:event_dimencion1ActionPerformed

    private void dimencion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dimencion2ActionPerformed
        routerDimension.mostrarDimension2Vista();
        monitorDimensiones.setVisible(true);
    }//GEN-LAST:event_dimencion2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        router.mostrarAutenticacionVista();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void pruebaDiagnosticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pruebaDiagnosticaActionPerformed
        router.mostrarEjercicioVista();
    }//GEN-LAST:event_pruebaDiagnosticaActionPerformed

    private void dimencion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dimencion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dimencion3ActionPerformed

    private void dimencio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dimencio4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dimencio4ActionPerformed

    private void dimencion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dimencion5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dimencion5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dimencio4;
    private javax.swing.JButton dimencion1;
    private javax.swing.JButton dimencion2;
    private javax.swing.JButton dimencion3;
    private javax.swing.JButton dimencion5;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel monitorDimensiones;
    private javax.swing.JButton pruebaDiagnostica;
    // End of variables declaration//GEN-END:variables
}
